[package]
name = "my_redis"
version = "0.1.0"
edition = "2021"

[dependencies]
#rt 表示开启单线程调度器，另外rt-multi-thread表示多线程的
tokio = { version = "1.40.0", features = ["net", "rt-multi-thread", "macros", "io-util"] }
once_cell = "1.19.0"
